package model;

import com.google.cloud.Timestamp;

public class TemperatureRecord {
    private String id;
    private String memberName;
    private String memberId;
    private Double temperature; // In Degree Celsius
    private Timestamp submissionDate;
    private String organisationCode;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMemberName() {
        return memberName;
    }

    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }

    public String getMemberId() {
        return memberId;
    }

    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    public Double getTemperature() {
        return temperature;
    }

    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    public Timestamp getSubmissionDate() {
        return submissionDate;
    }

    public void setSubmissionDate(Timestamp submissionDate) {
        this.submissionDate = submissionDate;
    }

    public String getOrganisationCode() {
        return organisationCode;
    }

    public void setOrganisationCode(String organisationCode) {
        this.organisationCode = organisationCode;
    }

    public TemperatureRecord() {}

    public TemperatureRecord(String memberName, String memberId, Double temperature, Timestamp submissionDate) {
        // Id is autogenerated by firebase hence we need not fill
        this.memberName = memberName;
        this.memberId = memberId;
        this.temperature = temperature;
        this.submissionDate = submissionDate;
    }
}
