package model;

import com.google.cloud.Timestamp;
import lombok.Data;
import util.StateManager;

import java.io.Serializable;

@Data
public class TemperatureRecord {
    private String id;
    private String organisationCode;
    private String name;
    private String telegramId;
    private Double temperature; // In Degree Celsius
    private Timestamp submissionDate;
    private Boolean isMember;

    public TemperatureRecord() {}

    // Cloning
    public TemperatureRecord(TemperatureRecord another) {
        this.id = another.id;
        this.organisationCode = another.organisationCode;
        this.name = another.name;
        this.telegramId = another.telegramId;
        this.temperature = another.temperature;
        this.submissionDate = another.submissionDate;
        this.isMember = another.isMember;
    }

    public TemperatureRecord(MemberRecord memberRecord) {
        this.id = null; // Id is irrelevant as we want only the fields information and also the fact that ids will not match
        this.organisationCode = StateManager.getCurrentOrg();
        this.name = memberRecord.getName();
        this.telegramId = memberRecord.getTelegramId();
        this.temperature = null;
        this.submissionDate = null;
        this.isMember = true;
    }

    public TemperatureRecord(String organisationCode, String name, String memberId, Double temperature, Timestamp submissionDate, Boolean isMember) {
        // ID is autogenerated by firebase hence we need not fill
        this.organisationCode = organisationCode;
        this.name = name;
        this.telegramId = memberId;
        this.temperature = temperature;
        this.submissionDate = submissionDate;
        this.isMember = isMember;
    }
}
