package model;

import com.google.cloud.Timestamp;

public class TemperatureRecord {
    private String id;
    private String organisationCode;
    private String name;
    private String telegramId;
    private Double temperature; // In Degree Celsius
    private Timestamp submissionDate;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTelegramId() {
        return telegramId;
    }

    public void setTelegramId(String telegramId) {
        this.telegramId = telegramId;
    }

    public Double getTemperature() {
        return temperature;
    }

    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    public Timestamp getSubmissionDate() {
        return submissionDate;
    }

    public void setSubmissionDate(Timestamp submissionDate) {
        this.submissionDate = submissionDate;
    }

    public String getOrganisationCode() {
        return organisationCode;
    }

    public void setOrganisationCode(String organisationCode) {
        this.organisationCode = organisationCode;
    }

    public TemperatureRecord() {}

    public TemperatureRecord(String organisationCode, String name, String memberId, Double temperature, Timestamp submissionDate) {
        // ID is autogenerated by firebase hence we need not fill
        this.organisationCode = organisationCode;
        this.name = name;
        this.telegramId = memberId;
        this.temperature = temperature;
        this.submissionDate = submissionDate;
    }
}
